### ISSUE TITLE
User NOT Found

### ISSUE THREAD

**Issue by sheikhartin** [PyFarsi/pyabr#13]
Why PyAbr shows user not found when used as a desktop app (not operating system)? How can I taste a *kind of national* OS?!

![Screenshot from 2022-06-04 09-43-27](https://user-images.githubusercontent.com/64385550/171985097-553d7e5a-1a36-4c1b-9021-ed7750246a7f.png)

**Comment by manijamali2003** [comment]
Hi
default user: root
default password: toor

**Comment by sheikhartin** [comment]
Aha, now it works :) But it's better to leave a note for the next users who wants to use like me in the main [README](https://github.com/PyFarsi/pyabr/blob/main/README.md) file of repository 👍🏼
