### ISSUE TITLE
VirtualBox

### ISSUE THREAD

**Issue by parsampsh** [PyFarsi/pyabr#5]
Hi guys. I was trying to install this operating system in the VirtualBox. I have downloaded the iso from your own website. but the OS was not booted. What do i do? Is there any required special configuration for the virtual machine?

**Comment by manijamali2003** [comment]
> Hi guys. I was trying to install this operating system in the VirtualBox. I have downloaded the iso from your own website. but the OS was not booted. What do i do? Is there any required special configuration for the virtual machine?

This is an unexpected and strange problem. (it should be quiet splash and slow process)

I was running it on Virtual box and it was working the best as qemu 

You can boot it on qemu with this  command:

qemu-img create pyabr.img 4G

qemu-system-x86_64 -m 1024 -cdrom pyabr_x86-64.iso -hda pyabr.img

**Comment by parsampsh** [comment]
thanks.
